import {
  Donation,
  AppointmentStatus,
  DonationStatus,
  BloodType,
  Sex,
} from "@/types";

export const donations: Donation[] = [
  {
    id: "d001",
    donor: {
      id: "donorA",
      name: "Alice Mendes",
      contactInfo: {
        email: "alice.mendes@email.com",
        phone: "16987654321",
        address: "Rua do Sol, 10",
      },
      cpf: "111.111.111-11",
      weight: 68,
      birthDate: "1985-02-28",
      sex: Sex.FEMALE,
      bloodType: BloodType.O_POS,
    },
    appointment: {
      id: "app001",
      appointmentDate: "2025-05-20",
      status: AppointmentStatus.COMPLETE,
      collectionSite: { id: "siteA", name: "Hemocentro Central" },
      notes: "Doação de rotina. Doadora saudável.",
    },
    donationStatus: DonationStatus.APPROVED,
    createdAt: "2025-05-20T10:00:00Z",
    updatedAt: "2025-05-20T11:30:00Z",
    notes: "Sem reações adversas. Bolsa coletada com sucesso.",
  },
  {
    id: "d002",
    donor: {
      id: "donorB",
      name: "Bruno Costa",
      contactInfo: {
        email: "bruno.costa@email.com",
        phone: "16912345678",
        address: "Avenida da Lua, 20",
      },
      cpf: "222.222.222-22",
      weight: 82,
      birthDate: "1979-11-11",
      sex: Sex.MALE,
      bloodType: BloodType.A_NEG,
    },
    appointment: {
      id: "app002",
      appointmentDate: "2025-05-21",
      status: AppointmentStatus.SCHEDULED,
      collectionSite: { id: "siteB", name: "Unidade Móvel B" },
      notes: "Primeira doação. Orientar sobre o processo.",
    },
    donationStatus: DonationStatus.UNDER_ANALYSIS,
    createdAt: "2025-05-21T09:30:00Z",
    updatedAt: "2025-05-21T09:30:00Z",
    notes: "Aguardando chegada do doador para triagem.",
  },
  {
    id: "d003",
    donor: {
      id: "donorC",
      name: "Carla Dias",
      contactInfo: {
        email: "carla.dias@email.com",
        phone: "16998765432",
        address: "Rua das Estrelas, 30",
      },
      cpf: "333.333.333-33",
      weight: 59,
      birthDate: "1998-07-03",
      sex: Sex.FEMALE,
      bloodType: BloodType.B_POS,
    },
    appointment: {
      id: "app003",
      appointmentDate: "2025-05-19",
      status: AppointmentStatus.COMPLETE,
      collectionSite: { id: "siteA", name: "Hemocentro Central" },
      notes: "Doadora regular. Sem histórico de problemas.",
    },
    donationStatus: DonationStatus.APPROVED,
    createdAt: "2025-05-19T14:15:00Z",
    updatedAt: "2025-05-19T15:00:00Z",
    notes: "Exames laboratoriais aprovados. Bolsa liberada.",
  },
  {
    id: "d004",
    donor: {
      id: "donorD",
      name: "Daniel Rocha",
      contactInfo: {
        email: "daniel.rocha@email.com",
        phone: "16911223344",
        address: "Avenida do Céu, 40",
      },
      cpf: "444.444.444-44",
      weight: 73,
      birthDate: "1990-01-01",
      sex: Sex.MALE,
      bloodType: BloodType.AB_NEG,
    },
    appointment: {
      id: "app004",
      appointmentDate: "2025-05-22",
      status: AppointmentStatus.CANCELED,
      collectionSite: { id: "siteB", name: "Unidade Móvel B" },
      notes: "Doador com febre. Reagendar.",
    },
    donationStatus: DonationStatus.REJECTED,
    createdAt: "2025-05-22T08:00:00Z",
    updatedAt: "2025-05-22T08:10:00Z",
    notes: "Cancelado devido a critérios de inaptidão temporária.",
  },
  {
    id: "d005",
    donor: {
      id: "donorE",
      name: "Eduarda Lima",
      contactInfo: {
        email: "eduarda.lima@email.com",
        phone: "16955667788",
        address: "Rua da Terra, 50",
      },
      cpf: "555.555.555-55",
      weight: 63,
      birthDate: "1996-09-17",
      sex: Sex.FEMALE,
      bloodType: BloodType.O_NEG,
    },
    appointment: {
      id: "app005",
      appointmentDate: "2025-05-23",
      status: AppointmentStatus.COMPLETE,
      collectionSite: { id: "siteA", name: "Hemocentro Central" },
      notes: "Doação de plaquetas. Processo mais longo.",
    },
    donationStatus: DonationStatus.APPROVED,
    createdAt: "2025-05-23T13:45:00Z",
    updatedAt: "2025-05-23T16:00:00Z",
    notes: "Plaquetas coletadas com sucesso. Doadora hidratada.",
  },
  {
    id: "d006",
    donor: {
      id: "donorF",
      name: "Fernando Gomes",
      contactInfo: {
        email: "fernando.gomes@email.com",
        phone: "16999887766",
        address: "Avenida do Mar, 60",
      },
      cpf: "666.666.666-66",
      weight: 76,
      birthDate: "1983-04-05",
      sex: Sex.MALE,
      bloodType: BloodType.B_NEG,
    },
    appointment: {
      id: "app006",
      appointmentDate: "2025-05-24",
      status: AppointmentStatus.SCHEDULED,
      collectionSite: { id: "siteC", name: "Clínica de Doação X" },
      notes: "Agendamento para doação de sangue total.",
    },
    donationStatus: DonationStatus.UNDER_ANALYSIS,
    createdAt: "2025-05-24T09:00:00Z",
    updatedAt: "2025-05-24T09:00:00Z",
    notes: "Aguardando triagem clínica.",
  },
  {
    id: "d007",
    donor: {
      id: "donorG",
      name: "Gabriela Nunes",
      contactInfo: {
        email: "gabriela.nunes@email.com",
        phone: "16911122233",
        address: "Rua da Floresta, 70",
      },
      cpf: "777.777.777-77",
      weight: 60,
      birthDate: "1991-10-20",
      sex: Sex.FEMALE,
      bloodType: BloodType.A_POS,
    },
    appointment: {
      id: "app007",
      appointmentDate: "2025-05-18",
      status: AppointmentStatus.COMPLETE,
      collectionSite: { id: "siteA", name: "Hemocentro Central" },
      notes: "Doadora nova, bem informada.",
    },
    donationStatus: DonationStatus.APPROVED,
    createdAt: "2025-05-18T11:00:00Z",
    updatedAt: "2025-05-18T12:00:00Z",
    notes: "Bolsa aprovada após exames. Sem intercorrências.",
  },
  {
    id: "d008",
    donor: {
      id: "donorH",
      name: "Henrique Pires",
      contactInfo: {
        email: "henrique.pires@email.com",
        phone: "16944556677",
        address: "Avenida da Montanha, 80",
      },
      cpf: "888.888.888-88",
      weight: 85,
      birthDate: "1975-03-14",
      sex: Sex.MALE,
      bloodType: BloodType.O_POS,
    },
    appointment: {
      id: "app008",
      appointmentDate: "2025-05-25",
      status: AppointmentStatus.SCHEDULED,
      collectionSite: { id: "siteC", name: "Clínica de Doação X" },
      notes: "Doador com histórico de viagens. Verificar critérios.",
    },
    donationStatus: DonationStatus.UNDER_ANALYSIS,
    createdAt: "2025-05-25T10:30:00Z",
    updatedAt: "2025-05-25T10:30:00Z",
    notes: "Aguardando avaliação médica para liberação.",
  },
  {
    id: "d009",
    donor: {
      id: "donorI",
      name: "Isabela Castro",
      contactInfo: {
        email: "isabela.castro@email.com",
        phone: "16977889900",
        address: "Rua do Rio, 90",
      },
      cpf: "999.999.999-99",
      weight: 57,
      birthDate: "1993-06-08",
      sex: Sex.FEMALE,
      bloodType: BloodType.AB_POS,
    },
    appointment: {
      id: "app009",
      appointmentDate: "2025-05-17",
      status: AppointmentStatus.COMPLETE,
      collectionSite: { id: "siteB", name: "Unidade Móvel B" },
      notes: "Doação em evento corporativo.",
    },
    donationStatus: DonationStatus.APPROVED,
    createdAt: "2025-05-17T09:00:00Z",
    updatedAt: "2025-05-17T10:15:00Z",
    notes: "Resultados dos exames em conformidade. Bolsa processada.",
  },
  {
    id: "d010",
    donor: {
      id: "donorJ",
      name: "João Victor",
      contactInfo: {
        email: "joao.victor@email.com",
        phone: "16922334455",
        address: "Avenida da Paz, 100",
      },
      cpf: "000.000.000-00",
      weight: 70,
      birthDate: "1980-12-01",
      sex: Sex.MALE,
      bloodType: BloodType.A_POS,
    },
    appointment: {
      id: "app010",
      appointmentDate: "2025-05-26",
      status: AppointmentStatus.SCHEDULED,
      collectionSite: { id: "siteA", name: "Hemocentro Central" },
      notes: "Doador com agendamento flexível.",
    },
    donationStatus: DonationStatus.UNDER_ANALYSIS,
    createdAt: "2025-05-26T08:45:00Z",
    updatedAt: "2025-05-26T08:45:00Z",
    notes: "Aguardando confirmação do agendamento.",
  },
];
