import {
  ImmunohemalogyExam,
  SerologicalScreeningExam,
  ExamStatus,
  DiseaseDetection,
  IrregularAntibodies,
  BloodType,
  Sex,
  AppointmentStatus,
  DonationStatus,
} from "@/types";

export const immunohemalogyExam: ImmunohemalogyExam = {
  id: "immuno-789",
  donation: {
    id: "d010",
    donor: {
      id: "donorJ",
      name: "João Victor",
      contactInfo: {
        email: "joao.victor@email.com",
        phone: "16922334455",
        address: "Avenida da Paz, 100",
      },
      cpf: "000.000.000-00",
      weight: 70,
      birthDate: "1980-12-01",
      sex: Sex.MALE,
      bloodType: BloodType.A_POSITIVE,
    },
    appointment: {
      id: "app010",
      appointmentDate: "2025-05-26",
      status: AppointmentStatus.SCHEDULED,
      collectionSite: { id: "siteA", name: "Hemocentro Central" },
      notes: "Doador com agendamento flexível.",
    },
    donationStatus: DonationStatus.UNDER_ANALYSIS,
    createdAt: "2025-05-26T08:45:00Z",
    updatedAt: "2025-05-26T08:45:00Z",
    notes: "Aguardando confirmação do agendamento.",
  },
  status: ExamStatus.APPROVED,
  createdAt: "2025-05-25T17:00:00-03:00",
  updatedAt: "2025-05-26T09:45:00-03:00",
  observations: "Sem aglutinações inesperadas.",
  bloodType: BloodType.B_NEG,
  irregularAntibodies: IrregularAntibodies.NEGATIVE,
};

export const serologicalExam: SerologicalScreeningExam = {
  id: "serological-123",
  donation: {
    id: "d009",
    donor: {
      id: "donorI",
      name: "Isabela Castro",
      contactInfo: {
        email: "isabela.castro@email.com",
        phone: "16977889900",
        address: "Rua do Rio, 90",
      },
      cpf: "999.999.999-99",
      weight: 57,
      birthDate: "1993-06-08",
      sex: Sex.FEMALE,
      bloodType: BloodType.AB_POSITIVE,
    },
    appointment: {
      id: "app009",
      appointmentDate: "2025-05-17",
      status: AppointmentStatus.COMPLETE,
      collectionSite: { id: "siteB", name: "Unidade Móvel B" },
      notes: "Doação em evento corporativo.",
    },
    donationStatus: DonationStatus.APPROVED,
    createdAt: "2025-05-17T09:00:00Z",
    updatedAt: "2025-05-17T10:15:00Z",
    notes: "Resultados dos exames em conformidade. Bolsa processada.",
  },
  status: ExamStatus.APPROVED,
  createdAt: "2025-05-25T18:00:00-03:00",
  updatedAt: "2025-05-26T10:30:00-03:00",
  observations: "Resultados dentro dos limites esperados.",
  hepatitisB: DiseaseDetection.NEGATIVE,
  hepatitisC: DiseaseDetection.NEGATIVE,
  chagasDisease: DiseaseDetection.NEGATIVE,
  syphilis: DiseaseDetection.NEGATIVE,
  aids: DiseaseDetection.NEGATIVE,
  htlv1_2: DiseaseDetection.NEGATIVE,
};
